# options.json → options_generated.h/.cpp 生成器(cmake -P 脚本)
# 用法: cmake -DJSON=<options.json> -DOUT_H=<out.h> -DOUT_CPP=<out.cpp> -P GenOptions.cmake
file(READ ${JSON} JS)

# ---- 收集全部顶层 key(形如 "quality.tier")----
string(JSON nOpt LENGTH ${JS})
set(ENTRIES "")
math(EXPR last "${nOpt} - 1")
foreach(i RANGE ${last})
  string(JSON key MEMBER ${JS} ${i})
  list(APPEND ENTRIES ${key})
endforeach()

set(H "")
set(C "")
string(APPEND H "// GENERATED FILE - 勿手改(由 cmake/GenOptions.cmake 生成)\n")
string(APPEND H "#pragma once\n#include <cstdint>\n#include <string>\n#include <vector>\n\n")
string(APPEND H "namespace rd {\n\n")
string(APPEND H "/// 声明式选项(唯一事实源:core/api/options.json)\n")
string(APPEND H "struct Options {\n")

# ---- struct 成员(按 . 前缀分组)----
set(GROUPS "")
foreach(E ${ENTRIES})
  string(REGEX MATCH "^[^.]+" G ${E})
  list(FIND GROUPS ${G} gi)
  if(gi EQUAL -1)
    list(APPEND GROUPS ${G})
    string(APPEND H "  struct ${G} {\n")
    foreach(K ${ENTRIES})
      if(K MATCHES "^${G}\\.")
        string(REGEX REPLACE "^${G}\\." "" M ${K})
        string(JSON type GET ${JS} ${K} type)
        string(JSON def GET ${JS} ${K} default)
        string(JSON doc GET ${JS} ${K} doc)
        if(type STREQUAL "bool")
          if(def STREQUAL "ON" OR def STREQUAL "TRUE")
            set(def "true")
          else()
            set(def "false")
          endif()
          string(APPEND H "    bool ${M} = ${def}\;  ///< ${doc}\n")
        elseif(type STREQUAL "int")
          string(APPEND H "    int32_t ${M} = ${def}\;  ///< ${doc}\n")
        elseif(type STREQUAL "float")
          string(APPEND H "    float ${M} = ${def}f\;  ///< ${doc}\n")
        elseif(type STREQUAL "enum")
          string(APPEND H "    std::string ${M} = \"${def}\"\;  ///< ${doc}\n")
        endif()
      endif()
    endforeach()
    string(APPEND H "  } ${G}\;\n")
  endif()
endforeach()
string(APPEND H "}\;\n\n")

string(APPEND H "/// 全部选项名(静态表)。\n")
string(APPEND H "const char* const* optionsAllNames()\;\n")
string(APPEND H "int32_t optionsCount()\;\n")
string(APPEND H "/// 读:值序列化到 out\;名不存在返回 false。\n")
string(APPEND H "bool optionsGet(const Options& o, const std::string& name, std::string& out)\;\n")
string(APPEND H "/// 写:字符串解析+域钳制\;名不存在/类型错/域外枚举返回 false。\n")
string(APPEND H "bool optionsSet(Options& o, const std::string& name, const std::string& value)\;\n")
string(APPEND H "/// 重置为默认。\n")
string(APPEND H "bool optionsReset(Options& o, const std::string& name)\;\n")
string(APPEND H "/// domain 段原文(UI 侧自解析\;无 domain 返回空串)。\n")
string(APPEND H "std::string optionsDomainJson(const std::string& name)\;\n")
string(APPEND H "/// range 域查询(有 range 域返回 true 并填 min/max/step)。\n")
string(APPEND H "bool optionsRange(const std::string& name, double& mn, double& mx, double& step)\;\n")
string(APPEND H "/// enum 域查询(有 enum 域返回 true 并填值表)。\n")
string(APPEND H "bool optionsEnumValues(const std::string& name, std::vector<std::string>& values)\;\n")
string(APPEND H "\n} // namespace rd\n")

# ---- cpp ----
string(APPEND C "// GENERATED FILE - 勿手改\n#include \"options_generated.h\"\n#include <algorithm>\n#include <vector>\n\n")
string(APPEND C "namespace rd {\nnamespace {\n")
string(APPEND C "const char* const kNames[] = {\n")
foreach(E ${ENTRIES})
  string(APPEND C "  \"${E}\",\n")
endforeach()
string(APPEND C "}\;\n} // namespace\n\n")
string(APPEND C "const char* const* optionsAllNames() { return kNames\; }\n")
string(APPEND C "int32_t optionsCount() { return int32_t(sizeof(kNames) / sizeof(kNames[0]))\; }\n\n")

string(APPEND C "bool optionsGet(const Options& o, const std::string& name, std::string& out) {\n")
foreach(E ${ENTRIES})
  string(JSON type GET ${JS} ${E} type)
  if(type STREQUAL "bool")
    string(APPEND C "  if (name == \"${E}\") { out = o.${E} ? \"true\" : \"false\"\; return true\; }\n")
  elseif(type STREQUAL "enum")
    string(APPEND C "  if (name == \"${E}\") { out = o.${E}\; return true\; }\n")
  else()
    string(APPEND C "  if (name == \"${E}\") { out = std::to_string(o.${E})\; return true\; }\n")
  endif()
endforeach()
string(APPEND C "  return false\;\n}\n\n")

string(APPEND C "bool optionsSet(Options& o, const std::string& name, const std::string& value) {\n")
foreach(E ${ENTRIES})
  string(JSON type GET ${JS} ${E} type)
  # 域探测:无 ERROR 支持(rc 兼容)——枚举条目成员名查 domain
  string(JSON nKeys LENGTH ${JS} ${E})
  math(EXPR lk "${nKeys} - 1")
  set(hasDom FALSE)
  foreach(ki RANGE ${lk})
    string(JSON kn MEMBER ${JS} ${E} ${ki})
    if(kn STREQUAL "domain")
      set(hasDom TRUE)
    endif()
  endforeach()
  if(type STREQUAL "bool")
    string(APPEND C "  if (name == \"${E}\") { o.${E} = value == \"true\" || value == \"1\"\; return true\; }\n")
  elseif(type STREQUAL "int")
    if(hasDom)
      string(JSON dmin GET ${JS} ${E} domain min)
      string(JSON dmax GET ${JS} ${E} domain max)
      string(APPEND C "  if (name == \"${E}\") { o.${E} = std::max(int32_t(${dmin}), std::min(int32_t(${dmax}), int32_t(std::stoi(value))))\; return true\; }\n")
    else()
      string(APPEND C "  if (name == \"${E}\") { o.${E} = int32_t(std::stoi(value))\; return true\; }\n")
    endif()
  elseif(type STREQUAL "float")
    if(hasDom)
      string(JSON dmin GET ${JS} ${E} domain min)
      string(JSON dmax GET ${JS} ${E} domain max)
      string(APPEND C "  if (name == \"${E}\") { o.${E} = std::max(float(${dmin}), std::min(float(${dmax}), std::stof(value)))\; return true\; }\n")
    else()
      string(APPEND C "  if (name == \"${E}\") { o.${E} = std::stof(value)\; return true\; }\n")
    endif()
  elseif(type STREQUAL "enum")
    string(JSON nVals LENGTH ${JS} ${E} domain values)
    string(APPEND C "  if (name == \"${E}\") {")
    math(EXPR lv "${nVals} - 1")
    foreach(i RANGE ${lv})
      string(JSON v GET ${JS} ${E} domain values ${i})
      string(APPEND C " if (value == \"${v}\") { o.${E} = value\; return true\; }")
    endforeach()
    string(APPEND C " return false\; }\n")
  endif()
endforeach()
string(APPEND C "  return false\;\n}\n\n")

string(APPEND C "bool optionsReset(Options& o, const std::string& name) {\n  Options d\;\n")
foreach(E ${ENTRIES})
  string(APPEND C "  if (name == \"${E}\") { o.${E} = d.${E}\; return true\; }\n")
endforeach()
string(APPEND C "  return false\;\n}\n\n")

string(APPEND C "std::string optionsDomainJson(const std::string& name) {\n")
foreach(E ${ENTRIES})
  string(JSON nKeys2 LENGTH ${JS} ${E})
  math(EXPR lk2 "${nKeys2} - 1")
  set(hasDom2 FALSE)
  foreach(ki2 RANGE ${lk2})
    string(JSON kn2 MEMBER ${JS} ${E} ${ki2})
    if(kn2 STREQUAL "domain")
      set(hasDom2 TRUE)
    endif()
  endforeach()
  set(domRaw "")
  if(hasDom2)
    string(JSON domRaw GET ${JS} ${E} domain)
  endif()
  if(hasDom2)
    # 域对象原文(GET 返回子 JSON 文本)
    string(REPLACE "\\" "\\\\" domRaw ${domRaw})
    string(REPLACE "\"" "\\\"" domRaw ${domRaw})
    string(REPLACE "\n" "" domRaw ${domRaw})
    string(APPEND C "  if (name == \"${E}\") return \"${domRaw}\"\;\n")
  endif()
endforeach()
string(APPEND C "  return \"\"\;\n}\n")
string(APPEND C "\n")
string(APPEND C "bool optionsRange(const std::string& name, double& mn, double& mx, double& step) {\n")
foreach(E ${ENTRIES})
  string(JSON type GET ${JS} ${E} type)
  if(NOT type STREQUAL "enum")
    string(JSON nKeys3 LENGTH ${JS} ${E})
    math(EXPR lk3 "${nKeys3} - 1")
    set(hasDom3 FALSE)
    foreach(ki3 RANGE ${lk3})
      string(JSON kn3 MEMBER ${JS} ${E} ${ki3})
      if(kn3 STREQUAL "domain")
        set(hasDom3 TRUE)
      endif()
    endforeach()
    if(hasDom3)
      string(JSON dmin GET ${JS} ${E} domain min)
      string(JSON dmax GET ${JS} ${E} domain max)
      string(JSON dstep GET ${JS} ${E} domain step)
      string(APPEND C "  if (name == \"${E}\") { mn = ${dmin}\; mx = ${dmax}\; step = ${dstep}\; return true\; }\n")
    endif()
  endif()
endforeach()
string(APPEND C "  return false\;\n}\n\n")
string(APPEND C "bool optionsEnumValues(const std::string& name, std::vector<std::string>& values) {\n")
foreach(E ${ENTRIES})
  string(JSON type GET ${JS} ${E} type)
  if(type STREQUAL "enum")
    string(JSON nVals2 LENGTH ${JS} ${E} domain values)
    string(APPEND C "  if (name == \"${E}\") {")
    math(EXPR lv2 "${nVals2} - 1")
    foreach(i2 RANGE ${lv2})
      string(JSON v2 GET ${JS} ${E} domain values ${i2})
      string(APPEND C " values.push_back(\"${v2}\")\;")
    endforeach()
    string(APPEND C " return true\; }\n")
  endif()
endforeach()
string(APPEND C "  return false\;\n}\n")
string(APPEND C "\n} // namespace rd\n")

file(WRITE ${OUT_H} ${H})
file(WRITE ${OUT_CPP} ${C})
